name: Build GUI for Windows - Processing 3

on:
  workflow_dispatch:
  pull_request:
    branches:
      - development

jobs:
  build:
    name: Build for Windows - Processing 3
    runs-on: windows-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3

    - name: Install Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        architecture: 'x64'
        cache: 'pip'

    - name: Set Path
      run: echo %GITHUB_WORKSPACE%\processing\processing-3.5.3>>%GITHUB_PATH%
      shell: cmd

    - name: Print Path
      run: echo %PATH%
      shell: cmd

    - name: Install Processing
      run: |
        mkdir processing
        cd %GITHUB_WORKSPACE%\processing
        curl -O -L --insecure https://download.processing.org/processing-3.5.3-windows64.zip
        ls -l %GITHUB_WORKSPACE%\processing
        unzip processing-3.5.3-windows64.zip
        ls -l %GITHUB_WORKSPACE%\processing\processing-3.5.3
        mkdir %userprofile%\documents\processing\libraries
        xcopy %GITHUB_WORKSPACE%\OpenBCI_GUI\libraries\* %userprofile%\documents\processing\libraries /s /i /q
        ls -l %userprofile%\documents\processing\libraries
      shell: cmd

    - name: Check processing-java
      run: processing-java --help
      shell: cmd

    - name: Build
      run: |
        python %GITHUB_WORKSPACE%\GuiUnitTests\run-unittests.py
        python %GITHUB_WORKSPACE%\release\build.py
      shell: cmd